name: Our First Workflow

on: push

jobs:
  build-test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup MSVC environment
        uses: ilammy/msvc-dev-cmd@v1

      - name: Build
        run: cl /nologo /W4 /EHsc main.c plus.c /Fe:main.exe

      - name: Test
        run: .\main.exe
